server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/chat_space_db
    username: chatdev
    password: 1234

file:
  upload-dir: C:/ClaudeCode/uploads
